// ================= Pollinator Lab — bilingual (TR/EN) data =================

// Static interface strings
export const UI = {
  en: {
    brandName: 'Canopy',
    brandSub: 'Biodiversity Field Lab',
    seasonTag: 'FIRST® CANOPY · 2026–27',
    pollinators: 'Canopy Life',
    speciesWord: 'species',
    groups: 'groups',
    todaysDiscovery: "Today's Discovery",
    back: '‹ Back to Collection',
    spotlight: 'Spotlight',
    notebook: 'Notebook', compare: 'Compare', share: 'Share',
    fieldGuide: 'Field Guide',
    flowerFit: 'Flower Fit',
    strataTitle: 'Forest Layer',
    strata: ['Emergent', 'Canopy', 'Understory', 'Forest Floor'],
    pollenNote: "This season's BIOBUZZ game element is Pollen — a tribute to the real pollinators that keep the canopy alive.",
    disclaimer: 'Fan-made educational build. Not affiliated with FIRST®.',
    quote: '"In every flower, a story. In every pollinator, a connection."',
    reset: 'Reset rotation', auto: 'Auto-rotate', fullscreen: 'Fullscreen',
    loading: 'Preparing specimen…',
    rail: { home: 'Home', explore: 'Explore', notes: 'Notes', garden: 'Garden', learn: 'Learn', math: 'Math' },
    factTitles: ['Species Details', 'Pollination Traits', 'Favorite Flowers', 'Range', 'Ecological Role'],
    overlay: {
      close: 'Close',
      garden: { title: 'Pollinator Garden', intro: "Every pollinator has its plants — here's who visits what across the canopy.", visitedBy: 'visited by' },
      notes: { title: 'Field Notes', intro: 'Discoveries collected in the field, one specimen at a time.' },
      learn: {
        title: 'About the Season',
        body: [
          'FIRST® CANOPY (2026–2027) is a biodiversity-themed robotics season. The FIRST Tech Challenge game — BIOBUZZ — even scores with “Pollen,” a direct nod to the pollinators celebrated in this lab.',
          'Pollinators carry pollen between flowers so plants can set seed and fruit. Bees, butterflies, moths, beetles, hummingbirds and bats together pollinate most flowering plants — and a large share of the food we eat.',
          'Rainforests are layered: the sunlit Emergent tops, the dense Canopy, the shaded Understory, and the Forest Floor. Each species here lives and feeds in its own layer.',
          'This is a fan-made educational tribute — not affiliated with FIRST®. Every 3D specimen is a Creative Commons model; attribution is shown beneath each one.',
        ],
      },
      math: {
        title: "Nature's Math",
        intro: 'Every specimen in this lab hides a math lesson. Each card follows the same path: concept → nature link → worked example → your turn.',
        labels: {
          concept: 'Concept',
          nature: 'In Nature',
          example: 'Worked Example',
          task: 'Your Turn',
          reveal: 'Show answer',
        },
      },
    },
  },
  tr: {
    brandName: 'Canopy',
    brandSub: 'Biyoçeşitlilik Saha Laboratuvarı',
    seasonTag: 'FIRST® CANOPY · 2026–27',
    pollinators: 'Canopy Yaşamı',
    speciesWord: 'tür',
    groups: 'grup',
    todaysDiscovery: 'Günün Keşfi',
    back: '‹ Koleksiyona Dön',
    spotlight: 'Vitrini',
    notebook: 'Defter', compare: 'Karşılaştır', share: 'Paylaş',
    fieldGuide: 'Saha Rehberi',
    flowerFit: 'Çiçek Uyumu',
    strataTitle: 'Orman Katmanı',
    strata: ['Tepe Örtüsü', 'Örtü (Canopy)', 'Alt Örtü', 'Orman Zemini'],
    pollenNote: 'Bu sezonun BIOBUZZ oyun elemanı Pollen — canopy’yi yaşatan gerçek tozlayıcılara bir selam.',
    disclaimer: 'Hayran yapımı, eğitim amaçlı proje. FIRST® ile bağlantılı değildir.',
    quote: '"Her çiçekte bir hikâye, her tozlayıcıda bir bağ vardır."',
    reset: 'Dönüşü sıfırla', auto: 'Otomatik döndür', fullscreen: 'Tam ekran',
    loading: 'Örnek hazırlanıyor…',
    rail: { home: 'Ana Sayfa', explore: 'Keşfet', notes: 'Notlar', garden: 'Bahçe', learn: 'Öğren', math: 'Matematik' },
    factTitles: ['Tür Bilgisi', 'Tozlaşma Özellikleri', 'Sevdiği Çiçekler', 'Yayılış', 'Ekolojik Rol'],
    overlay: {
      close: 'Kapat',
      garden: { title: 'Tozlayıcı Bahçesi', intro: 'Her tozlayıcının kendi bitkileri vardır — işte canopy boyunca kimin neyi ziyaret ettiği.', visitedBy: 'ziyaretçisi:' },
      notes: { title: 'Saha Notları', intro: 'Sahada, her seferinde bir örnek toplanarak kaydedilen keşifler.' },
      learn: {
        title: 'Sezon Hakkında',
        body: [
          'FIRST® CANOPY (2026–2027), biyoçeşitlilik temalı bir robotik sezonudur. FIRST Tech Challenge oyunu — BIOBUZZ — skor elemanı olarak “Pollen”i kullanır; bu, bu laboratuvarda kutlanan tozlayıcılara doğrudan bir selamdır.',
          'Tozlayıcılar, bitkilerin tohum ve meyve verebilmesi için çiçekler arasında polen taşır. Arılar, kelebekler, güveler, böcekler, sinekkuşları ve yarasalar birlikte çiçekli bitkilerin çoğunu — ve yediğimiz gıdanın büyük bölümünü — tozlar.',
          'Yağmur ormanları katmanlıdır: güneşli Tepe Örtüsü, yoğun Örtü (Canopy), gölgeli Alt Örtü ve Orman Zemini. Buradaki her tür kendi katmanında yaşar ve beslenir.',
          'Bu, hayran yapımı, eğitim amaçlı bir projedir — FIRST® ile bağlantılı değildir. Tüm 3D örnekler Creative Commons modellerdir; atıf her birinin altında gösterilir.',
        ],
      },
      math: {
        title: 'Doğanın Matematiği',
        intro: 'Bu laboratuvardaki her örnek bir matematik dersi saklar. Her kart aynı yolu izler: kavram → doğa bağlantısı → çözümlü örnek → sıra sende.',
        labels: {
          concept: 'Kavram',
          nature: 'Doğada',
          example: 'Çözümlü Örnek',
          task: 'Sıra Sende',
          reveal: 'Cevabı göster',
        },
      },
    },
  },
};

// ============ Nature's Math — one structured lesson per specimen ============
// Teaching structure per lesson: topic → concept → nature link → worked
// example → practice task → answer. `id` matches the POLLINATORS entry.
export const MATH_LESSONS = [
  {
    id: 'bees', emoji: '🐝', icon: '⬡',
    en: {
      topic: 'Geometry — Hexagons & Tiling',
      concept: 'A regular hexagon has 6 equal sides and 6 equal angles. Hexagons tile a surface with no gaps, using the least wall for the most storage area.',
      nature: 'Bees build honeycomb from hexagonal wax cells — the most material-efficient shape that still tiles perfectly.',
      example: 'Interior angles of any hexagon sum to (6 − 2) × 180° = 720°. In a regular hexagon each angle is 720° ÷ 6 = 120°.',
      task: 'Three honeycomb cells meet at every corner. What do their three 120° angles add up to — and why does that make the tiling gap-free?',
      answer: '120° + 120° + 120° = 360°, a full turn — so the cells close around each corner with no gap.',
    },
    tr: {
      topic: 'Geometri — Altıgenler ve Döşeme',
      concept: 'Düzgün altıgenin 6 eş kenarı ve 6 eş açısı vardır. Altıgenler bir yüzeyi boşluksuz döşer; en az duvarla en çok depolama alanı sağlar.',
      nature: 'Arılar peteği altıgen mum hücrelerden örer — hem kusursuz döşenen hem de en az malzeme isteyen şekil budur.',
      example: 'Bir altıgenin iç açıları toplamı (6 − 2) × 180° = 720° eder. Düzgün altıgende her açı 720° ÷ 6 = 120° olur.',
      task: 'Her köşede üç petek hücresi buluşur. Üç 120°’lik açının toplamı kaçtır — ve bu, döşemeyi neden boşluksuz yapar?',
      answer: '120° + 120° + 120° = 360°, yani tam tur — hücreler her köşeyi boşluk bırakmadan kapatır.',
    },
  },
  {
    id: 'wasps', emoji: '🐝', icon: '×2',
    en: {
      topic: 'Numbers — Doubling & Powers',
      concept: 'When a quantity doubles at each step, it grows as powers of 2: after n doublings you have 2ⁿ times what you started with.',
      nature: 'A wasp colony starts with a single queen in spring; as workers raise more workers, the paper nest can double its population again and again.',
      example: 'One doubling: 1 → 2. Three doublings: 1 → 2 → 4 → 8, which is 2³ = 8.',
      task: 'A young nest holds 50 wasps and doubles every week. How many wasps after 4 weeks?',
      answer: '50 × 2⁴ = 50 × 16 = 800 wasps.',
    },
    tr: {
      topic: 'Sayılar — İkiye Katlama ve Kuvvetler',
      concept: 'Bir çokluk her adımda ikiye katlanırsa 2’nin kuvvetleriyle büyür: n katlamadan sonra başlangıcın 2ⁿ katına ulaşırsın.',
      nature: 'Yaban arısı kolonisi baharda tek bir kraliçeyle başlar; işçiler yeni işçiler büyüttükçe kâğıt yuvanın nüfusu tekrar tekrar ikiye katlanabilir.',
      example: 'Bir katlama: 1 → 2. Üç katlama: 1 → 2 → 4 → 8, yani 2³ = 8.',
      task: 'Genç bir yuvada 50 yaban arısı var ve sayı her hafta ikiye katlanıyor. 4 hafta sonra kaç yaban arısı olur?',
      answer: '50 × 2⁴ = 50 × 16 = 800 yaban arısı.',
    },
  },
  {
    id: 'moths', emoji: '🌙', icon: '◑',
    en: {
      topic: 'Symmetry & Averages',
      concept: 'A shape has line (mirror) symmetry when one half is the exact reflection of the other. The mean of a range is (smallest + largest) ÷ 2.',
      nature: 'The giant peacock moth is a living mirror: each wing’s eyespot reflects its twin across the body line. Its wingspan ranges from 15 to 20 cm.',
      example: 'A butterfly-shaped figure folded along its body line matches perfectly — that fold is the line of symmetry.',
      task: 'Estimate a typical wingspan: what is the mean of the 15–20 cm range?',
      answer: '(15 + 20) ÷ 2 = 17.5 cm.',
    },
    tr: {
      topic: 'Simetri ve Ortalama',
      concept: 'Bir şeklin bir yarısı diğerinin tam yansımasıysa doğru (ayna) simetrisi vardır. Bir aralığın ortalaması (en küçük + en büyük) ÷ 2 ile bulunur.',
      nature: 'Dev tavus güvesi yaşayan bir aynadır: her kanattaki göz beneği, gövde çizgisine göre ikizini yansıtır. Kanat açıklığı 15–20 cm arasındadır.',
      example: 'Kelebek biçimli bir şekil gövde çizgisinden katlanınca üst üste çakışır — o katlama çizgisi simetri doğrusudur.',
      task: 'Tipik bir kanat açıklığını tahmin et: 15–20 cm aralığının ortalaması kaçtır?',
      answer: '(15 + 20) ÷ 2 = 17,5 cm.',
    },
  },
  {
    id: 'butterflies', emoji: '🦋', icon: '⇢',
    en: {
      topic: 'Rate — Distance, Speed & Time',
      concept: 'Distance, speed and time are linked: time = distance ÷ speed. Keep the units consistent and the formula does the rest.',
      nature: 'Monarchs migrate up to 4,000 km, flying roughly 80 km on a good day — a journey so long it spans generations.',
      example: 'A 240 km leg at 80 km per day takes 240 ÷ 80 = 3 days.',
      task: 'At 80 km per day, how many flying days does the full 4,000 km migration take?',
      answer: '4,000 ÷ 80 = 50 flying days.',
    },
    tr: {
      topic: 'Oran — Yol, Hız ve Zaman',
      concept: 'Yol, hız ve zaman birbirine bağlıdır: zaman = yol ÷ hız. Birimleri tutarlı seçersen gerisini formül halleder.',
      nature: 'Kral kelebekleri 4.000 km’ye varan göç yapar; iyi bir günde yaklaşık 80 km uçarlar — yolculuk nesillere yayılacak kadar uzundur.',
      example: '240 km’lik bir etap, günde 80 km hızla 240 ÷ 80 = 3 gün sürer.',
      task: 'Günde 80 km ile 4.000 km’lik göçün tamamı kaç uçuş günü sürer?',
      answer: '4.000 ÷ 80 = 50 uçuş günü.',
    },
  },
  {
    id: 'beetles', emoji: '🪲', icon: '%',
    en: {
      topic: 'Fractions & Percentages',
      concept: 'A fraction compares a part to a whole; multiply by 100 to express it as a percentage.',
      nature: 'Beetles are the most diverse animal group on Earth — roughly 400,000 named species, about one quarter of all known animal species.',
      example: '1/4 as a percentage: (1 ÷ 4) × 100 = 25%.',
      task: 'Of about 1,000,000 named insect species, 400,000 are beetles. What percentage is that?',
      answer: '(400,000 ÷ 1,000,000) × 100 = 40%.',
    },
    tr: {
      topic: 'Kesirler ve Yüzdeler',
      concept: 'Kesir, parçayı bütünle karşılaştırır; 100 ile çarparak yüzdeye çevirirsin.',
      nature: 'Böcekler yeryüzünün en çeşitli hayvan grubudur — adlandırılmış yaklaşık 400.000 tür, bilinen tüm hayvan türlerinin dörtte biri kadar.',
      example: '1/4’ün yüzdesi: (1 ÷ 4) × 100 = %25.',
      task: 'Adlandırılmış yaklaşık 1.000.000 böcek türünün 400.000’i kın kanatlıdır. Bu yüzde kaçtır?',
      answer: '(400.000 ÷ 1.000.000) × 100 = %40.',
    },
  },
  {
    id: 'hummingbirds', emoji: '🐦', icon: '♒',
    en: {
      topic: 'Frequency & Big Multiplication',
      concept: 'Frequency counts events per unit of time. To change the time unit, multiply: per-second × 60 gives per-minute.',
      nature: 'A ruby-throated hummingbird beats its wings up to 80 times every second — too fast for the eye, easy for arithmetic.',
      example: '80 beats/second × 60 = 4,800 beats per minute.',
      task: 'How many wingbeats in a 5-minute feeding flight at 80 beats per second?',
      answer: '80 × 60 × 5 = 24,000 wingbeats.',
    },
    tr: {
      topic: 'Frekans ve Büyük Sayılarla Çarpma',
      concept: 'Frekans, birim zamandaki olay sayısıdır. Zaman birimini değiştirmek için çarparsın: saniyedeki × 60, dakikadakini verir.',
      nature: 'Yakut boğazlı sinekkuşu kanatlarını saniyede 80 kez çırpar — göz için çok hızlı, aritmetik için çok kolay.',
      example: 'Saniyede 80 çırpış × 60 = dakikada 4.800 çırpış.',
      task: 'Saniyede 80 çırpışla 5 dakikalık bir beslenme uçuşunda kaç kanat çırpışı olur?',
      answer: '80 × 60 × 5 = 24.000 kanat çırpışı.',
    },
  },
  {
    id: 'bats', emoji: '🦇', icon: '∿',
    en: {
      topic: 'Measurement — Speed of Sound',
      concept: 'Sound travels about 340 metres per second. An echo covers the distance twice (there and back), so distance = (speed × time) ÷ 2.',
      nature: 'Nectar bats navigate the dark with echolocation: they call, listen for the echo, and time it to map cactus flowers ahead.',
      example: 'An echo returning after 0.02 s: (340 × 0.02) ÷ 2 = 3.4 m to the flower.',
      task: 'A bat hears its echo 0.1 seconds after calling. How far away is the saguaro?',
      answer: '(340 × 0.1) ÷ 2 = 17 metres.',
    },
    tr: {
      topic: 'Ölçme — Sesin Hızı',
      concept: 'Ses saniyede yaklaşık 340 metre yol alır. Yankı mesafeyi iki kez kat eder (gidiş-dönüş), bu yüzden mesafe = (hız × süre) ÷ 2.',
      nature: 'Nektar yarasaları karanlıkta ekolokasyonla yön bulur: seslenir, yankıyı dinler ve süresini ölçerek öndeki kaktüs çiçeklerinin haritasını çıkarır.',
      example: '0,02 saniyede dönen yankı: (340 × 0,02) ÷ 2 = çiçeğe 3,4 m.',
      task: 'Bir yarasa seslendikten 0,1 saniye sonra yankıyı duyuyor. Sagualo kaktüsü ne kadar uzakta?',
      answer: '(340 × 0,1) ÷ 2 = 17 metre.',
    },
  },
];

// Per-species content. `latin` is shared; everything else has en/tr.
export const POLLINATORS = [
  {
    id: 'bees', emoji: '🐝', guideNo: 'No. 07', latin: 'Euglossa dilemma', layer: 1,
    factIcons: ['🔬', '🌸', '✿', '🗺', '🌿'],
    en: {
      cat: 'Bees', count: '~20,000 species', family: 'Apidae Family',
      name: 'Orchid Bee',
      chips: ['Neotropical', 'Diurnal', 'Solitary', 'Fragrance Collector'],
      discovery: 'Orchid bees collect fragrances to attract mates. They store scent in specialized leg pockets!',
      facts: [
        'Medium-sized bee (11–15 mm). Males are brilliantly iridescent; females are dark with green highlights.',
        'Visits a wide variety of flowers. Uses strong flight and agility to access complex blooms.',
        'Orchids, Catasetum, Stanhopea, Vanilla, Passiflora, and fragrant forest flowers.',
        'Central America to northern South America. From Mexico to Brazil.',
        'Important pollinator of orchids and other forest plants.',
      ],
      flower: 'Cattleya Orchid',
    },
    tr: {
      cat: 'Arılar', count: '~20.000 tür', family: 'Apidae Familyası',
      name: 'Orkide Arısı',
      chips: ['Neotropik', 'Gündüzcül', 'Yalnız Yaşar', 'Koku Toplayıcı'],
      discovery: 'Orkide arıları eş çekmek için kokular toplar ve bu kokuları bacaklarındaki özel ceplerde saklar!',
      facts: [
        'Orta boy arı (11–15 mm). Erkekler parlak yanardöner renklidir; dişiler yeşil vurgulu koyu renktedir.',
        'Çok çeşitli çiçeği ziyaret eder. Güçlü uçuşu ve çevikliğiyle karmaşık çiçeklere ulaşır.',
        'Orkideler, Catasetum, Stanhopea, Vanilya, Passiflora ve kokulu orman çiçekleri.',
        'Orta Amerika’dan kuzey Güney Amerika’ya; Meksika’dan Brezilya’ya kadar.',
        'Orkidelerin ve diğer orman bitkilerinin önemli tozlayıcısıdır.',
      ],
      flower: 'Cattleya Orkidesi',
    },
    flowerArt: '🪻',
  },
  {
    id: 'wasps', emoji: '🐝', guideNo: 'No. 09', latin: 'Vespula vulgaris', layer: 2,
    factIcons: ['🔬', '🌸', '✿', '🗺', '🌿'],
    en: {
      cat: 'Wasps', count: '~100,000 species', family: 'Vespidae Family',
      name: 'Common Wasp',
      chips: ['Cosmopolitan', 'Diurnal', 'Social', 'Nectar & Prey'],
      discovery: "Wasps aren't only predators — sugar-hungry adults sip nectar and pollinate flowers like figwort and some orchids along the way!",
      facts: [
        'A social yellow-and-black wasp (12–17 mm) living in large paper nests built from chewed wood fibre.',
        'Adults feed on nectar and honeydew, carrying pollen as they move between shallow flowers.',
        'Figwort (Scrophularia), ivy, and other shallow, easily reached blooms.',
        'Native across Europe and Asia; introduced widely, including Australia and New Zealand.',
        'Both pollinator and top insect predator — a natural check on pest populations.',
      ],
      flower: 'Figwort',
    },
    tr: {
      cat: 'Yaban Arıları', count: '~100.000 tür', family: 'Vespidae Familyası',
      name: 'Yaban Arısı',
      chips: ['Kozmopolit', 'Gündüzcül', 'Sosyal', 'Nektar & Avcı'],
      discovery: 'Yaban arıları yalnızca avcı değildir — şekere aç yetişkinler nektar emer ve yolda sıraca otu ile bazı orkideleri tozlar!',
      facts: [
        'Çiğnenmiş odun lifinden yaptığı büyük kâğıt yuvalarda yaşayan, sarı-siyah sosyal bir yaban arısı (12–17 mm).',
        'Yetişkinler nektar ve ballıçiy ile beslenir; sığ çiçekler arasında dolaşırken polen taşır.',
        'Sıraca otu (Scrophularia), sarmaşık ve diğer sığ, kolay ulaşılan çiçekler.',
        'Avrupa ve Asya kökenli; Avustralya ve Yeni Zelanda dahil geniş alana taşınmıştır.',
        'Hem tozlayıcı hem de üst düzey böcek avcısı — zararlı popülasyonlarına doğal bir denge.',
      ],
      flower: 'Sıraca Otu',
    },
    flowerArt: '🌸',
  },
  {
    id: 'moths', emoji: '🌙', guideNo: 'No. 12', latin: 'Saturnia pyri', layer: 2,
    factIcons: ['🔬', '🌙', '✿', '🗺', '🌿'],
    en: {
      cat: 'Moths', count: '~160,000 species', family: 'Saturniidae Family',
      name: 'Giant Peacock Moth',
      chips: ['Palearctic', 'Nocturnal', 'Eyespotted', 'Silk Moth'],
      discovery: "Europe's largest moth wears four eyespots to startle predators — and males can track a female's scent from kilometres away!",
      facts: [
        'The largest moth in Europe, with a wingspan of 15–20 cm and a bold eyespot on each wing.',
        'Adults barely feed, living on stored energy — but the many moths that do visit flowers are vital night-shift pollinators.',
        'Pale, fragrant, night-blooming flowers that guide moths through the dark.',
        'Southern Europe, North Africa and western Asia, in orchards and open woodland.',
        'A giant of the night; its caterpillars and adults feed birds, bats and other predators.',
      ],
      flower: 'Night Jasmine',
    },
    tr: {
      cat: 'Güveler', count: '~160.000 tür', family: 'Saturniidae Familyası',
      name: 'Dev Tavus Güvesi',
      chips: ['Palearktik', 'Gececil', 'Göz Benekli', 'İpek Güvesi'],
      discovery: 'Avrupa’nın en büyük güvesi, avcıları ürkütmek için dört göz beneği taşır — erkekler dişinin kokusunu kilometrelerce öteden izleyebilir!',
      facts: [
        'Avrupa’nın en büyük güvesi; kanat açıklığı 15–20 cm ve her kanadında belirgin bir göz beneği bulunur.',
        'Yetişkinler neredeyse hiç beslenmez, depoladıkları enerjiyle yaşar — ama çiçek ziyaret eden pek çok güve gecenin kilit tozlayıcısıdır.',
        'Güveleri karanlıkta yönlendiren soluk renkli, kokulu, geceleri açan çiçekler.',
        'Güney Avrupa, Kuzey Afrika ve batı Asya’da; meyve bahçeleri ve açık ormanlarda.',
        'Gecenin devi; tırtılları ve yetişkinleri kuşları, yarasaları ve diğer avcıları besler.',
      ],
      flower: 'Gece Yasemini',
    },
    flowerArt: '🌼',
  },
  {
    id: 'butterflies', emoji: '🦋', guideNo: 'No. 05', latin: 'Danaus plexippus', layer: 1,
    factIcons: ['🔬', '🌸', '✿', '🗺', '🌿'],
    en: {
      cat: 'Butterflies', count: '~18,500 species', family: 'Nymphalidae Family',
      name: 'Monarch',
      chips: ['Nearctic', 'Diurnal', 'Migratory', 'Nectar Lover'],
      discovery: 'Monarchs migrate up to 4,000 km — and it takes several generations to complete the round trip!',
      facts: [
        'A large orange-and-black butterfly (9–10 cm wingspan), famous for its multi-generation migration.',
        'Sips nectar through a coiled proboscis, dusting flowers with pollen as it feeds by day.',
        'Milkweed for its caterpillars; nectar from asters, goldenrod, coneflower and many blooms.',
        'The Americas — with vast overwintering roosts in central Mexico and coastal California.',
        'A flagship pollinator and an icon of insect migration and conservation.',
      ],
      flower: 'Milkweed',
    },
    tr: {
      cat: 'Kelebekler', count: '~18.500 tür', family: 'Nymphalidae Familyası',
      name: 'Kral Kelebeği',
      chips: ['Nearktik', 'Gündüzcül', 'Göçmen', 'Nektar Sever'],
      discovery: 'Kral kelebekleri 4.000 km’ye kadar göç eder — ve gidiş-dönüşü tamamlamak birkaç nesil sürer!',
      facts: [
        'Çok nesilli göçüyle ünlü, büyük turuncu-siyah bir kelebek (9–10 cm kanat açıklığı).',
        'Kıvrık hortumuyla nektar emer; gündüz beslenirken çiçeklere polen bulaştırır.',
        'Tırtılları için ipek otu; asterler, altınbaşak, ekinezya ve birçok çiçekten nektar.',
        'Amerika kıtası — orta Meksika ve California kıyılarında devasa kışlama toplulukları.',
        'Amiral bir tozlayıcı; böcek göçünün ve doğa korumanın simgesi.',
      ],
      flower: 'İpek Otu',
    },
    flowerArt: '🌷',
  },
  {
    id: 'beetles', emoji: '🪲', guideNo: 'No. 21', latin: 'Golofa sp.', layer: 2,
    factIcons: ['🔬', '🌸', '✿', '🗺', '🌿'],
    en: {
      cat: 'Beetles', count: '~400,000 species', family: 'Scarabaeidae Family',
      name: 'Rhinoceros Beetle',
      chips: ['Neotropical', 'Montane', 'Horned', 'Sap Feeder'],
      discovery: 'Male Golofa rhinoceros beetles duel with long horns for mates — grappling like sumo wrestlers on bamboo stems!',
      facts: [
        'A montane rhinoceros beetle. Males bear a long thoracic horn and a curved head horn used in contests over females.',
        'Beetles are among the most ancient flower visitors; feeding on sap and blooms, they carry pollen from plant to plant.',
        'Sap flows, fermenting fruit, and large open blooms of the cloud-forest canopy.',
        'Montane cloud forests of Central and South America, often among bamboo.',
        'Part of the beetle lineage — the oldest pollinators — and a key recycler of forest plant matter.',
      ],
      flower: 'Cloud-Forest Bloom',
    },
    tr: {
      cat: 'Böcekler', count: '~400.000 tür', family: 'Scarabaeidae Familyası',
      name: 'Gergedan Böceği',
      chips: ['Neotropik', 'Dağlık', 'Boynuzlu', 'Öz Su Emen'],
      discovery: 'Erkek Golofa gergedan böcekleri dişiler için uzun boynuzlarıyla düello yapar — bambu saplarında sumo güreşçileri gibi itişirler!',
      facts: [
        'Dağlık bölgelerde yaşayan bir gergedan böceği. Erkeklerde, dişiler için mücadelede kullanılan uzun bir göğüs boynuzu ve kıvrık bir baş boynuzu bulunur.',
        'Böcekler en kadim çiçek ziyaretçileri arasındadır; öz su ve çiçeklerle beslenirken bitkiden bitkiye polen taşırlar.',
        'Öz su akıntıları, mayalanan meyveler ve bulut ormanı örtüsündeki büyük açık çiçekler.',
        'Orta ve Güney Amerika’nın dağlık bulut ormanları; sıklıkla bambular arasında.',
        'En eski tozlayıcılar olan böcek soyunun parçası ve orman bitki maddesinin önemli bir geri dönüştürücüsü.',
      ],
      flower: 'Bulut Ormanı Çiçeği',
    },
    flowerArt: '🌼',
  },
  {
    id: 'hummingbirds', emoji: '🐦', guideNo: 'No. 03', latin: 'Archilochus colubris', layer: 1,
    factIcons: ['🔬', '🌺', '✿', '🗺', '🌿'],
    en: {
      cat: 'Hummingbirds', count: '~360 species', family: 'Trochilidae Family',
      name: 'Ruby-throated',
      chips: ['Nearctic', 'Diurnal', 'Hovering', 'Nectar Specialist'],
      discovery: 'A hummingbird beats its wings up to 80 times per second and can hover, fly backward, even upside down!',
      facts: [
        'Tiny bird (7–9 cm) with iridescent green back and a brilliant ruby gorget in males.',
        'Hovers to sip nectar through a long bill and brush-tipped tongue, dusting its head with pollen.',
        'Red and orange tubular flowers — trumpet vine, bee balm, fuchsia, and cardinal flower.',
        'Eastern North America; migrates across the Gulf of Mexico to Central America.',
        'Primary pollinator of many tubular, scentless, brightly colored flowers.',
      ],
      flower: 'Trumpet Vine',
    },
    tr: {
      cat: 'Sinekkuşları', count: '~360 tür', family: 'Trochilidae Familyası',
      name: 'Yakut Boğazlı',
      chips: ['Nearktik', 'Gündüzcül', 'Havada Asılı', 'Nektar Uzmanı'],
      discovery: 'Bir sinekkuşu saniyede 80 kez kanat çırpabilir; havada asılı durabilir, geri geri, hatta ters uçabilir!',
      facts: [
        'Yanardöner yeşil sırtlı, erkeklerde parlak yakut renkli boğazı olan küçük bir kuş (7–9 cm).',
        'Uzun gagası ve fırça uçlu diliyle nektar emmek için havada asılı durur; başına polen bulaşır.',
        'Kırmızı ve turuncu boru çiçekleri — borazan çiçeği, arı otu, küpe çiçeği ve kardinal çiçeği.',
        'Doğu Kuzey Amerika; Meksika Körfezi üzerinden Orta Amerika’ya göç eder.',
        'Birçok borumsu, kokusuz, canlı renkli çiçeğin başlıca tozlayıcısı.',
      ],
      flower: 'Borazan Çiçeği',
    },
    flowerArt: '🌺',
  },
  {
    id: 'bats', emoji: '🦇', guideNo: 'No. 17', latin: 'Leptonycteris yerbabuenae', layer: 0,
    factIcons: ['🔬', '🌵', '✿', '🗺', '🌙'],
    en: {
      cat: 'Bats', count: '~1,400 species', family: 'Phyllostomidae Family',
      name: 'Lesser Long-nosed',
      chips: ['Neotropical', 'Nocturnal', 'Hovering', 'Nectar Feeder'],
      discovery: 'Nectar bats pollinate the giant saguaro and agave — without them, there would be no tequila!',
      facts: [
        'Medium bat with an elongated muzzle and a long, bristled tongue for reaching deep nectar.',
        'Hovers at large night flowers, carrying pollen on its furry face between distant plants.',
        'Large, pale, night-opening flowers — agave, saguaro, organ-pipe cactus, and ceiba.',
        'Southwestern USA through Mexico; follows a "nectar corridor" of blooming agave.',
        'Keystone pollinator of desert cacti and agave across arid landscapes.',
      ],
      flower: 'Agave Bloom',
    },
    tr: {
      cat: 'Yarasalar', count: '~1.400 tür', family: 'Phyllostomidae Familyası',
      name: 'Küçük Uzun Burunlu',
      chips: ['Neotropik', 'Gececil', 'Havada Asılı', 'Nektarla Beslenen'],
      discovery: 'Nektar yarasaları dev sagualo kaktüsünü ve agavı tozlar — onlar olmasa tekila da olmazdı!',
      facts: [
        'Uzamış burnu ve derin nektara ulaşmak için uzun, kıllı bir dili olan orta boy bir yarasa.',
        'Büyük gece çiçeklerinde havada asılı durur; tüylü yüzünde uzak bitkiler arasında polen taşır.',
        'Büyük, soluk, geceleri açan çiçekler — agav, sagualo, org borusu kaktüsü ve ceiba.',
        'Güneybatı ABD’den Meksika’ya; çiçeklenen agavların oluşturduğu bir "nektar koridorunu" izler.',
        'Kurak coğrafyalarda çöl kaktüsleri ve agavların anahtar tozlayıcısı.',
      ],
      flower: 'Agav Çiçeği',
    },
    flowerArt: '🌵',
  },
];
